---
# Install required packages
- include: requirements.yml

# Install Contiki-OS
- name: Clone repository
  git:
    repo: "https://github.com/contiki-os/contiki.git"
    dest: "{{ contiki_root }}"
    force: yes
    recursive: yes
    accept_hostkey: yes
  become: yes
  become_user: vagrant
