---
- name: Install required libraries
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - ant
    - libncurses5-dev
    - lib32ncurses5
    - libopenblas-dev
    - liblapack-dev
    - gfortran
    - imagemagick

- name: Install required Python libraries
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-numpy
    - python-scipy

- name: Install Java
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - "{{ current_jdk }}-jdk"
    - "{{ current_jdk }}-jre"
    - ant

- name: Install AVR GCC Toolchain
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - gcc-avr
    - binutils-avr
    - gdb-avr
    - avr-libc
    - avrdude

- name: Install msp430 tools
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - lib32z1
    - binutils-msp430
    - gcc-msp430
    - msp430-libc
    - msp430mcu
    - mspdebug
