---
- name: Create the RPL Attacks Framework appliance
  hosts: rpl-attacks-framework
  user: vagrant
  sudo: yes
  roles:
    - baseline
    - contiki-os
    - rpl-attacks
    - hardening
  vars:
    current_jdk: openjdk-8
    private_network: 192.168.27.0/24
    contiki_root: ~/contiki
    rplaf_root: ~/rpl-attacks
    keyboard_layout: be
    sidebar_launchers: "['application://rpl-attacks-framework.desktop','application://nautilus.desktop','application://terminator.desktop','application://firefox.desktop','application://gedit.desktop','unity://running-apps','unity://devices']"
