---
# Install required packages
- include: requirements.yml

# Install RPLAF
- block:

  - name: Clone repository
    git:
      repo: "https://github.com/dhondta/rpl-attacks.git"
      dest: "{{ rplaf_root }}"
      force: yes
      recursive: no
      accept_hostkey: yes

  - name: Clean deployment artifacts
    file:
      path: "{{ rplaf_root }}/{{ item }}"
      state: absent
    with_items:
      - provisioning
      - Vagrantfile

  - name: Install Python requirements
    pip:
      requirements: "{{ rplaf_root }}/requirements.txt"
    sudo: yes

  - name: Change main Python script's mode to executable
    file:
      dest: "{{ rplaf_root }}/main.py"
      mode: 0744

  - name: Copy configuration file
    template:
      src: .rpl-attacks.conf
      dest: "~/"

  - name: Copy wallpaper
    copy:
      src: wallpaper.png
      dest: "~/Pictures/"

  - name: Set wallpaper
    shell: |
      PID=$(pgrep gnome-session)
      export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)
      gsettings set org.gnome.desktop.background picture-uri file:///home/$USER/Pictures/wallpaper.png

  - name: Test RPL Attacks Framework
    command: fab test
    args:
      chdir: "{{ rplaf_root }}"

  - name: Move shortcut to system shortcuts folder
    command: mv ~/Desktop/rpl-attacks-framework.desktop ~/.local/share/applications/
    ignore_errors: True

  - name: Reconfigure Unity launchers
    shell: |
      PID=$(pgrep gnome-session)
      export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)
      gsettings set com.canonical.Unity.Launcher favorites "{{ sidebar_launchers }}"

  - name: Add a shortcut to Experiments on the desktop
    command: 
    args: ln -s ~/Experiments ~/Desktop/Experiments

  become: yes
  become_user: vagrant
