---
# Specific process for the VmWare box
- name: Remove box custom repo
  file: dest=/etc/apt/sources.list.d/puppetlabs.list
        state=absent

# Locale
- name: Configure Locale
  locale_gen:
    name: en_US.UTF-8
    state: present

# Keyboard layout
- name: Set keyboard layout
  lineinfile:
    dest: /etc/default/keyboard
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - { regexp: 'XKBMODEL=', line: 'XKBMODEL="pc105"' }
    - { regexp: 'XKBLAYOUT=', line: 'XKBLAYOUT="{{ keyboard_layout }}"' }
  notify: Restart system

# Apt
- name: Update APT cache and all packages
  apt:
    update_cache: yes
    upgrade: dist

# Global packages
- name: Install baseline packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - biosdevname
    - vim
    - htop
    - screen
    - iotop
    - iptables
    - ipset
    - tcpdump

# Install basic packages
- include: packages.yml

# Upgrade Python Pip
- name: Upgrade Pip
  pip:
    name: pip
    extra_args: --upgrade
