---
- name: Install common libraries
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - ubuntu-desktop
    - build-essential
    - doxygen
    - gfortran
    - imagemagick
    - terminator

- name: Install Python stuffs
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-dev
    - python-pip

- name: Install Git
  apt:
    pkg: git
    state: latest

- name: Install Open VM Tools
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - open-vm-tools
    - open-vm-tools-dev      
    - open-vm-tools-desktop
